name: eosdx
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - python-dotenv=1.0.1
  - awscli=2.15.55
  - black=24.4.2
  - click=8.1.7
  - coverage=7.5.1
  - dvc=3.50.2
  - dvc-s3=3.2.0
  - flake8=7.0.0
  - h5py=3.11.0
  - hydra-core=1.3.2
  - interrogate=1.7.0
  - ipykernel=6.29.3
  - ipympl=0.9.4
  - isort=5.13.2
  - matplotlib=3.8.4
  - mlflow=2.13.0
  - numpy=1.26.4
  - numpydoc=1.7.0
  - pandas=2.2.2
  - pre-commit=3.7.1
  - pyFAI=2024.5.0
  - pytest=8.2.1
  - scikit-image=0.22.0
  - scikit-learn=1.5.0
  - scipy=1.13.0
  - seaborn=0.13.2
  - shap=0.45.1
  - sphinx=7.3.7
  - xgboost=2.0.3
