channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.5.2
  - numpy=1.22.4
  - numpydoc=1.4.0
  - pandas=1.4.2
  - pip=22.1.2
  - scikit-image=0.19.3
  - scikit-learn=1.1.1
  - scipy=1.9.1
  - sphinx=5.1.1
