channels:
  - conda-forge
dependencies:
  - python=3.10.4
  - matplotlib=3.5.2
  - numpy=1.22.4
  - numpydoc=1.4.0
  - pandas=1.4.2
  - scikit-image=0.19.3
  - scikit-learn=1.2.2
  - scipy=1.9.1
  - sphinx=5.1.1
  - sphinx-automodapi=0.16.0
  - pydata-sphinx-theme=0.15.2
