<<<<<<< HEAD
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
=======
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eosdxanalysis"
version = "2.77.5"
authors = [
  { name="Jonathan Friedman", email="jfriedman@eosdx.com" },
>>>>>>> main
]
