<<<<<<< HEAD
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eosdxanalysis"
version = "2.77.5"
authors = [
  { name="Jonathan Friedman", email="jfriedman@eosdx.com" },
=======
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
>>>>>>> f1b68e8c2981c9492f42f2d96f7777ae0adeaf3b
]
