# -*- coding: utf-8 -*-
"""
Motivational phrases for the Ulster application.
"""

motivation_phrases = [
    "Believe you can and you're halfway there.",
    "Keep going, keep growing.",
    "Every day is a new opportunity.",
    "Dream it. Wish it. Do it.",
    "Don't stop until you're proud.",
    "The best time to start was yesterday. The next best is now.",
    "Success is the sum of small efforts repeated day in and day out.",
    "You are stronger than you think.",
    "Turn your wounds into wisdom.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Don't wait for opportunity. Create it.",
    "It's going to be hard, but hard does not mean impossible.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream bigger. Do bigger.",
    "Stay positive. Work hard. Make it happen.",
    "Don't wish for it. Work for it.",
    "Little by little, day by day.",
    "You didn't come this far to only come this far.",
    "Believe in yourself and all that you are.",
    "You are your only limit.",
    "Difficult roads often lead to beautiful destinations.",
    "The only way to do great work is to love what you do.",
    "You don't have to be perfect to be amazing.",
    "Start each day with a grateful heart.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Act as if what you do makes a difference. It does.",
    "The secret of getting ahead is getting started.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Do something today that your future self will thank you for.",
    "Don’t limit your challenges. Challenge your limits.",
    "It always seems impossible until it’s done.",
    "Your limitation—it’s only your imagination.",
    "Success is not for the lazy.",
    "The future depends on what you do today.",
    "What defines us is how well we rise after falling.",
    "Don’t count the days; make the days count.",
    "You are capable of amazing things.",
    "Only those who risk going too far can possibly find out how far one can go.",
    "You miss 100% of the shots you don’t take.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Fall seven times, stand up eight.",
    "The way to get started is to quit talking and begin doing.",
    "You are never too old to set a new goal or dream a new dream.",
    "If you can dream it, you can do it.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Don’t let yesterday take up too much of today.",
    "Failure is the condiment that gives success its flavor.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Don't be afraid to give up the good to go for the great.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The harder the battle, the sweeter the victory.",
    "When you feel like quitting, remember why you started.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "Success isn't always about greatness. It's about consistency.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "The purpose of our lives is to be happy.",
    "A river cuts through rock not because of its power but its persistence.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "We generate fears while we sit. We overcome them by action.",
    "Start where you are. Use what you have. Do what you can.",
    "Opportunities don't happen. You create them.",
    "Your passion is waiting for your courage to catch up.",
    "Magic is believing in yourself. If you can make that happen, you can make anything happen.",
    "All our dreams can come true, if we have the courage to pursue them.",
    "Hard work beats talent when talent doesn’t work hard.",
    "If not us, who? If not now, when?",
    "The journey of a thousand miles begins with one step.",
    "Success usually comes to those who are too busy to be looking for it.",
    "There are no limits to what you can accomplish, except the limits you place on your own thinking.",
    "Don't limit yourself. Many people limit themselves to what they think they can do.",
    "Always do your best. What you plant now, you will harvest later.",
    "Change your life today. Don't gamble on the future. Act now, without delay.",
    "Strive not to be a success, but rather to be of value.",
    "The secret to getting results is to never stop working.",
    "Believe in the power of yet. You’re not there yet.",
    "Failure is success if we learn from it.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success is the best revenge.",
    "You don’t drown by falling in the water; you drown by staying there.",
    "If you want to achieve greatness stop asking for permission.",
    "We may encounter many defeats but we must not be defeated.",
    "Only put off until tomorrow what you are willing to die having left undone.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Dreams don’t work unless you do.",
    "You have to expect things of yourself before you can do them.",
    "The best revenge is massive success.",
    "Action is the foundational key to all success.",
    "The key to success is to focus on goals, not obstacles.",
    "Excellence is not a skill. It’s an attitude.",
    "The biggest risk is not taking any risk.",
    "Don’t let fear decide your future.",
    "Embrace the glorious mess that you are.",
    "Progress, not perfection.",
]
