# Macro file for Example1
#
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threaded mode)
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
# Set a very high time threshold to allow all decays to happen
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year
#
/gun/particle gamma
/gun/energy 6 MeV
#
/run/beamOn 100
