"""Dummy detector backend used in demo mode and tests."""

import threading
import time

import numpy as np

from hardware.difra.hardware.detector_controller_base import DetectorController
from hardware.difra.utils.logger import (
    get_module_logger,
    log_hardware_state,
    with_logging,
)

logger = get_module_logger(__name__)


class DummyDetectorController(DetectorController):
    def __init__(self, alias="DUMMY", size=(256, 256)):
        self.alias = alias
        self.size = size
        self._stream_thread = None
        self._streaming = threading.Event()
        logger.debug("Initialized DummyDetectorController", detector=alias, size=size)

    @log_hardware_state("dev")
    @with_logging("detector_init")
    def init_detector(self):
        logger.detector_event(self.alias, "initialization started")
        logger.detector_event(self.alias, "initialization completed")
        return True

    def capture_point(self, Nframes, Nseconds, filename_base):
        filename = f"{filename_base}.txt"
        self._dummy_acquire(filename, Nseconds, Nframes)
        return True

    def _dummy_acquire(self, filename, Nseconds, Nframes=1):
        target_duration_s = max(float(Nseconds), 0.0) * max(int(Nframes), 1)
        started_at = time.perf_counter()
        width, height = self.size

        integrated = np.zeros((height, width), dtype=float)
        for _ in range(max(int(Nframes), 1)):
            x, y = np.arange(width), np.arange(height)
            X, Y = np.meshgrid(x, y)
            x0, y0 = np.random.uniform(0, width), np.random.uniform(0, height)
            sigma = np.random.uniform(5, min(width, height) / 4)
            amp = np.random.uniform(1e5, 2e6)
            frame = amp * np.exp(-(((X - x0) ** 2 + (Y - y0) ** 2) / (2 * sigma**2)))
            frame += np.random.normal(scale=amp * 0.1, size=frame.shape)
            integrated += frame

        np.savetxt(filename, integrated, fmt="%.6f")
        logger.file_operation(
            "save",
            filename,
            detector=self.alias,
            integration_time=Nseconds,
            frames=Nframes,
        )

        dsc_filename = filename.replace(".txt", ".dsc")
        self._generate_fake_dsc(dsc_filename, Nseconds, Nframes, integrated)

        elapsed = time.perf_counter() - started_at
        remaining = target_duration_s - elapsed
        if remaining > 0:
            if remaining > 0.003:
                time.sleep(remaining - 0.0015)
            while (time.perf_counter() - started_at) < target_duration_s:
                pass

    def _generate_fake_dsc(self, dsc_filename, Nseconds, Nframes, data):
        import datetime

        width, height = self.size
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        total_time = float(Nseconds) * max(int(Nframes), 1)
        dsc_content = f"""[F0]
Type=i16 [X,Y,C] width={width} height={height}
Acq mode=INTEGRATING
Acq time={total_time:.6f}
Frames={Nframes}
Start time={timestamp}
ChipboardID=DEMO-{self.alias}
Interface=USB
Pixel size=0.055 mm
Layout=1x1
# DEMO MODE - Fake descriptor file
# Generated by DummyDetectorController
# Detector: {self.alias}
# Total counts: {data.sum():.0f}
# Max value: {data.max():.0f}
# Mean value: {data.mean():.2f}
"""
        try:
            with open(dsc_filename, "w", encoding="utf-8") as f:
                f.write(dsc_content)
            logger.file_operation(
                "save",
                dsc_filename,
                detector=self.alias,
                integration_time=Nseconds,
                frames=Nframes,
                file_type="descriptor",
            )
        except Exception as e:
            logger.warning(
                "Failed to generate .dsc file",
                detector=self.alias,
                error=str(e),
            )

    @with_logging("detector_deinit")
    def deinit_detector(self):
        logger.detector_event(self.alias, "deinitialization completed")

    def start_stream(self, callback, exposure=0.1, interval=0.0, frames=1):
        self.stop_stream()
        self._streaming.set()
        self._stream_thread = threading.Thread(
            target=self._stream_loop,
            args=(callback, exposure, interval),
            daemon=True,
        )
        self._stream_thread.start()
        logger.detector_event(self.alias, "streaming started", exposure=exposure)

    def stop_stream(self):
        if self._stream_thread and self._stream_thread.is_alive():
            self._streaming.clear()
            self._stream_thread.join(timeout=2.0)
            logger.detector_event(self.alias, "streaming stopped")
        self._stream_thread = None

    def _stream_loop(self, callback, exposure, interval):
        width, height = self.size
        while self._streaming.is_set():
            x, y = np.arange(width), np.arange(height)
            X, Y = np.meshgrid(x, y)
            x0, y0 = np.random.uniform(0, width), np.random.uniform(0, height)
            sigma = np.random.uniform(5, min(width, height) / 4)
            amp = np.random.uniform(1e5, 2e6)
            frame = amp * np.exp(-(((X - x0) ** 2 + (Y - y0) ** 2) / (2 * sigma**2)))
            frame += np.random.normal(scale=amp * 0.1, size=frame.shape)
            callback({self.alias: frame})
            time.sleep(exposure)
            if interval:
                time.sleep(interval)

    def convert_to_container_format(
        self,
        raw_file_path: str,
        container_version: str = "0.2",
    ) -> str:
        from pathlib import Path

        raw_path = Path(raw_file_path)
        if container_version == "0.2":
            npy_path = raw_path.with_suffix(".npy")
            if not npy_path.exists():
                try:
                    data = np.loadtxt(raw_path)
                    np.save(npy_path, data)
                    logger.info(
                        "Converted detector output for container format",
                        container_version=container_version,
                        detector=self.alias,
                        input_file=raw_path.name,
                        output_file=npy_path.name,
                    )
                except Exception as e:
                    raise RuntimeError(f"Failed to convert {raw_path} to .npy: {e}")
            else:
                logger.debug(
                    "Container format file already exists",
                    detector=self.alias,
                    file=npy_path.name,
                )
            return str(npy_path)
        raise ValueError(
            f"Detector {self.alias} does not support container version {container_version}"
        )

    def get_raw_file_patterns(self):
        return ["*.txt", "*.dsc"]
