# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hub.v1 import hub_pb2 as hub_dot_v1_dot_hub__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hub/v1/hub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AcquisitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartExposure = channel.unary_unary(
                '/hub.v1.Acquisition/StartExposure',
                request_serializer=hub_dot_v1_dot_hub__pb2.StartExposureRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/hub.v1.Acquisition/Pause',
                request_serializer=hub_dot_v1_dot_hub__pb2.PauseRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/hub.v1.Acquisition/Resume',
                request_serializer=hub_dot_v1_dot_hub__pb2.ResumeRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/hub.v1.Acquisition/Stop',
                request_serializer=hub_dot_v1_dot_hub__pb2.StopRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/hub.v1.Acquisition/Abort',
                request_serializer=hub_dot_v1_dot_hub__pb2.AbortRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/hub.v1.Acquisition/GetState',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.GetLastExposureResult = channel.unary_unary(
                '/hub.v1.Acquisition/GetLastExposureResult',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.GetExposureResultResponse.FromString,
                _registered_method=True)
        self.StartBackgroundMeasurement = channel.unary_unary(
                '/hub.v1.Acquisition/StartBackgroundMeasurement',
                request_serializer=hub_dot_v1_dot_hub__pb2.StartBackgroundMeasurementRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.BackgroundMeasurementResponse.FromString,
                _registered_method=True)
        self.SubscribeRunEvents = channel.unary_stream(
                '/hub.v1.Acquisition/SubscribeRunEvents',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.SystemEvent.FromString,
                _registered_method=True)


class AcquisitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartExposure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastExposureResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBackgroundMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRunEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcquisitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartExposure': grpc.unary_unary_rpc_method_handler(
                    servicer.StartExposure,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.StartExposureRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.PauseRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.ResumeRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.StopRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.AbortRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.GetStateResponse.SerializeToString,
            ),
            'GetLastExposureResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastExposureResult,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.GetExposureResultResponse.SerializeToString,
            ),
            'StartBackgroundMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBackgroundMeasurement,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.StartBackgroundMeasurementRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.BackgroundMeasurementResponse.SerializeToString,
            ),
            'SubscribeRunEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRunEvents,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.SystemEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.Acquisition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.Acquisition', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Acquisition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartExposure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Acquisition/StartExposure',
            hub_dot_v1_dot_hub__pb2.StartExposureRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Acquisition/Pause',
            hub_dot_v1_dot_hub__pb2.PauseRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Acquisition/Resume',
            hub_dot_v1_dot_hub__pb2.ResumeRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Acquisition/Stop',
            hub_dot_v1_dot_hub__pb2.StopRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Acquisition/Abort',
            hub_dot_v1_dot_hub__pb2.AbortRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Acquisition/GetState',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLastExposureResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Acquisition/GetLastExposureResult',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.GetExposureResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBackgroundMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Acquisition/StartBackgroundMeasurement',
            hub_dot_v1_dot_hub__pb2.StartBackgroundMeasurementRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.BackgroundMeasurementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRunEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hub.v1.Acquisition/SubscribeRunEvents',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.SystemEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MotionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MoveTo = channel.unary_unary(
                '/hub.v1.Motion/MoveTo',
                request_serializer=hub_dot_v1_dot_hub__pb2.MoveToRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.MoveRelative = channel.unary_unary(
                '/hub.v1.Motion/MoveRelative',
                request_serializer=hub_dot_v1_dot_hub__pb2.MoveRelativeRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.Home = channel.unary_unary(
                '/hub.v1.Motion/Home',
                request_serializer=hub_dot_v1_dot_hub__pb2.HomeRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/hub.v1.Motion/Stop',
                request_serializer=hub_dot_v1_dot_hub__pb2.StopRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.SetVelocity = channel.unary_unary(
                '/hub.v1.Motion/SetVelocity',
                request_serializer=hub_dot_v1_dot_hub__pb2.SetVelocityRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPosition = channel.unary_unary(
                '/hub.v1.Motion/GetPosition',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.GetPositionResponse.FromString,
                _registered_method=True)


class MotionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MoveTo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveRelative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Home(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MoveTo': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveTo,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.MoveToRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'MoveRelative': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveRelative,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.MoveRelativeRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'Home': grpc.unary_unary_rpc_method_handler(
                    servicer.Home,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.HomeRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.StopRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'SetVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVelocity,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.SetVelocityRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.GetPositionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.Motion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.Motion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Motion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MoveTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Motion/MoveTo',
            hub_dot_v1_dot_hub__pb2.MoveToRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveRelative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Motion/MoveRelative',
            hub_dot_v1_dot_hub__pb2.MoveRelativeRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Home(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Motion/Home',
            hub_dot_v1_dot_hub__pb2.HomeRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Motion/Stop',
            hub_dot_v1_dot_hub__pb2.StopRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Motion/SetVelocity',
            hub_dot_v1_dot_hub__pb2.SetVelocityRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Motion/GetPosition',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.GetPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PowerDevice = channel.unary_unary(
                '/hub.v1.DeviceControl/PowerDevice',
                request_serializer=hub_dot_v1_dot_hub__pb2.PowerDeviceRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.GetDetectorHealth = channel.unary_unary(
                '/hub.v1.DeviceControl/GetDetectorHealth',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.DetectorHealth.FromString,
                _registered_method=True)
        self.GetMotionHealth = channel.unary_unary(
                '/hub.v1.DeviceControl/GetMotionHealth',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.MotionHealth.FromString,
                _registered_method=True)
        self.GetDeviceState = channel.unary_unary(
                '/hub.v1.DeviceControl/GetDeviceState',
                request_serializer=hub_dot_v1_dot_hub__pb2.DeviceStateRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.DeviceStateResponse.FromString,
                _registered_method=True)


class DeviceControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PowerDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetectorHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMotionHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PowerDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerDevice,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.PowerDeviceRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'GetDetectorHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetectorHealth,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.DetectorHealth.SerializeToString,
            ),
            'GetMotionHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMotionHealth,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.MotionHealth.SerializeToString,
            ),
            'GetDeviceState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceState,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.DeviceStateRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.DeviceStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.DeviceControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.DeviceControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PowerDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.DeviceControl/PowerDevice',
            hub_dot_v1_dot_hub__pb2.PowerDeviceRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDetectorHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.DeviceControl/GetDetectorHealth',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.DetectorHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMotionHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.DeviceControl/GetMotionHealth',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.MotionHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.DeviceControl/GetDeviceState',
            hub_dot_v1_dot_hub__pb2.DeviceStateRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.DeviceStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SafetyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInterlockStatus = channel.unary_unary(
                '/hub.v1.Safety/GetInterlockStatus',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.InterlockStatus.FromString,
                _registered_method=True)
        self.ResetInterlocks = channel.unary_unary(
                '/hub.v1.Safety/ResetInterlocks',
                request_serializer=hub_dot_v1_dot_hub__pb2.CommandContext.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.CheckSafetyToOperate = channel.unary_unary(
                '/hub.v1.Safety/CheckSafetyToOperate',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.InterlockStatus.FromString,
                _registered_method=True)


class SafetyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInterlockStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetInterlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSafetyToOperate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SafetyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInterlockStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterlockStatus,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.InterlockStatus.SerializeToString,
            ),
            'ResetInterlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetInterlocks,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.CommandContext.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'CheckSafetyToOperate': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSafetyToOperate,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.InterlockStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.Safety', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.Safety', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Safety(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInterlockStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Safety/GetInterlockStatus',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.InterlockStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetInterlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Safety/ResetInterlocks',
            hub_dot_v1_dot_hub__pb2.CommandContext.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSafetyToOperate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Safety/CheckSafetyToOperate',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.InterlockStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Liveness = channel.unary_unary(
                '/hub.v1.Health/Liveness',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.Readiness = channel.unary_unary(
                '/hub.v1.Health/Readiness',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAggregateHealth = channel.unary_unary(
                '/hub.v1.Health/GetAggregateHealth',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.AggregateHealth.FromString,
                _registered_method=True)


class HealthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Liveness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Readiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregateHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Liveness': grpc.unary_unary_rpc_method_handler(
                    servicer.Liveness,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'Readiness': grpc.unary_unary_rpc_method_handler(
                    servicer.Readiness,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'GetAggregateHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregateHealth,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.AggregateHealth.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.Health', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Liveness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Health/Liveness',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Readiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Health/Readiness',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAggregateHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.Health/GetAggregateHealth',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.AggregateHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StateMonitorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToStateUpdates = channel.unary_stream(
                '/hub.v1.StateMonitor/SubscribeToStateUpdates',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.StateChangeNotification.FromString,
                _registered_method=True)
        self.SubscribeIncidents = channel.unary_stream(
                '/hub.v1.StateMonitor/SubscribeIncidents',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.IncidentEvent.FromString,
                _registered_method=True)
        self.GetFullServerState = channel.unary_unary(
                '/hub.v1.StateMonitor/GetFullServerState',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.FullServerStateResponse.FromString,
                _registered_method=True)
        self.GetGpioState = channel.unary_unary(
                '/hub.v1.StateMonitor/GetGpioState',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.GpioStateResponse.FromString,
                _registered_method=True)
        self.GetDetectorState = channel.unary_unary(
                '/hub.v1.StateMonitor/GetDetectorState',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.DetectorStateResponse.FromString,
                _registered_method=True)
        self.GetMotionState = channel.unary_unary(
                '/hub.v1.StateMonitor/GetMotionState',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.MotionStateResponse.FromString,
                _registered_method=True)


class StateMonitorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeToStateUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeIncidents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullServerState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGpioState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetectorState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMotionState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeToStateUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToStateUpdates,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.StateChangeNotification.SerializeToString,
            ),
            'SubscribeIncidents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeIncidents,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.IncidentEvent.SerializeToString,
            ),
            'GetFullServerState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullServerState,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.FullServerStateResponse.SerializeToString,
            ),
            'GetGpioState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGpioState,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.GpioStateResponse.SerializeToString,
            ),
            'GetDetectorState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetectorState,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.DetectorStateResponse.SerializeToString,
            ),
            'GetMotionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMotionState,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.MotionStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.StateMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.StateMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateMonitor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeToStateUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hub.v1.StateMonitor/SubscribeToStateUpdates',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.StateChangeNotification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeIncidents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hub.v1.StateMonitor/SubscribeIncidents',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.IncidentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullServerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.StateMonitor/GetFullServerState',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.FullServerStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGpioState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.StateMonitor/GetGpioState',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.GpioStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDetectorState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.StateMonitor/GetDetectorState',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.DetectorStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMotionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.StateMonitor/GetMotionState',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.MotionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DeviceInitializationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeDetector = channel.unary_unary(
                '/hub.v1.DeviceInitialization/InitializeDetector',
                request_serializer=hub_dot_v1_dot_hub__pb2.InitializeDetectorRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.DetectorStateResponse.FromString,
                _registered_method=True)
        self.InitializeMotion = channel.unary_unary(
                '/hub.v1.DeviceInitialization/InitializeMotion',
                request_serializer=hub_dot_v1_dot_hub__pb2.InitializeMotionRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.MotionStateResponse.FromString,
                _registered_method=True)
        self.PowerOffDetector = channel.unary_unary(
                '/hub.v1.DeviceInitialization/PowerOffDetector',
                request_serializer=hub_dot_v1_dot_hub__pb2.CommandContext.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)
        self.PowerOffMotion = channel.unary_unary(
                '/hub.v1.DeviceInitialization/PowerOffMotion',
                request_serializer=hub_dot_v1_dot_hub__pb2.CommandContext.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                _registered_method=True)


class DeviceInitializationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeDetector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeMotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PowerOffDetector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PowerOffMotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceInitializationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeDetector': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeDetector,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.InitializeDetectorRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.DetectorStateResponse.SerializeToString,
            ),
            'InitializeMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeMotion,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.InitializeMotionRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.MotionStateResponse.SerializeToString,
            ),
            'PowerOffDetector': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerOffDetector,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.CommandContext.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
            'PowerOffMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerOffMotion,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.CommandContext.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.DeviceInitialization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.DeviceInitialization', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceInitialization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeDetector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.DeviceInitialization/InitializeDetector',
            hub_dot_v1_dot_hub__pb2.InitializeDetectorRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.DetectorStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.DeviceInitialization/InitializeMotion',
            hub_dot_v1_dot_hub__pb2.InitializeMotionRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.MotionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PowerOffDetector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.DeviceInitialization/PowerOffDetector',
            hub_dot_v1_dot_hub__pb2.CommandContext.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PowerOffMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.DeviceInitialization/PowerOffMotion',
            hub_dot_v1_dot_hub__pb2.CommandContext.SerializeToString,
            hub_dot_v1_dot_hub__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CommandDiscoveryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerCapabilities = channel.unary_unary(
                '/hub.v1.CommandDiscovery/GetServerCapabilities',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.GetServerCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ListCommands = channel.unary_unary(
                '/hub.v1.CommandDiscovery/ListCommands',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.ListCommandsResponse.FromString,
                _registered_method=True)
        self.ValidateCompatibility = channel.unary_unary(
                '/hub.v1.CommandDiscovery/ValidateCompatibility',
                request_serializer=hub_dot_v1_dot_hub__pb2.ValidateCompatibilityRequest.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.ValidateCompatibilityResponse.FromString,
                _registered_method=True)
        self.GetCommandReadiness = channel.unary_unary(
                '/hub.v1.CommandDiscovery/GetCommandReadiness',
                request_serializer=hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
                response_deserializer=hub_dot_v1_dot_hub__pb2.GetCommandReadinessResponse.FromString,
                _registered_method=True)


class CommandDiscoveryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCompatibility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandReadiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandDiscoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerCapabilities,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.GetServerCapabilitiesResponse.SerializeToString,
            ),
            'ListCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCommands,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.ListCommandsResponse.SerializeToString,
            ),
            'ValidateCompatibility': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCompatibility,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.ValidateCompatibilityRequest.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.ValidateCompatibilityResponse.SerializeToString,
            ),
            'GetCommandReadiness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandReadiness,
                    request_deserializer=hub_dot_v1_dot_hub__pb2.Empty.FromString,
                    response_serializer=hub_dot_v1_dot_hub__pb2.GetCommandReadinessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hub.v1.CommandDiscovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hub.v1.CommandDiscovery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommandDiscovery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.CommandDiscovery/GetServerCapabilities',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.GetServerCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.CommandDiscovery/ListCommands',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.ListCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCompatibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.CommandDiscovery/ValidateCompatibility',
            hub_dot_v1_dot_hub__pb2.ValidateCompatibilityRequest.SerializeToString,
            hub_dot_v1_dot_hub__pb2.ValidateCompatibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandReadiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hub.v1.CommandDiscovery/GetCommandReadiness',
            hub_dot_v1_dot_hub__pb2.Empty.SerializeToString,
            hub_dot_v1_dot_hub__pb2.GetCommandReadinessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
