//! Data encryption and HIPAA compliance for medical device operations
//! 
//! Implements requirements from USER_EXPECTATIONS.md Section 3:
//! - Zero data loss with immediate persistence
//! - HIPAA-compliant security with AES-256-GCM encryption
//! - Encrypt all data at rest
//! - Encrypt data in transit using TLS 1.2+
//! - Log all data access events
//! - Store credentials and encryption keys in hardware-protected storage (TPM)
//! - Automated backup with verification

use aes_gcm::{
    aead::{Aead, KeyInit, OsRng, generic_array::GenericArray},
    Aes256Gcm,
};
use anyhow::{Result, anyhow};
use base64::{Engine as _, engine::general_purpose};
use rand::RngCore;
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Encrypted data container
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EncryptedData {
    /// Base64-encoded ciphertext
    pub ciphertext: String,
    /// Base64-encoded nonce (96-bit)
    pub nonce: String,
    /// Version of encryption scheme
    pub version: u32,
}

/// Data encryption service
pub struct EncryptionService {
    cipher: Aes256Gcm,
}

impl EncryptionService {
    /// Create new encryption service with provided key
    /// 
    /// TODO: Integrate with TPM for hardware-backed key storage
    /// For production, keys should be:
    /// 1. Generated by TPM
    /// 2. Never exposed in plaintext
    /// 3. Bound to specific hardware
    /// 4. Backed up securely with key escrow
    pub fn new(key: &[u8; 32]) -> Result<Self> {
        let cipher = Aes256Gcm::new(key.into());
        Ok(Self { cipher })
    }
    
    /// Generate a new random encryption key
    /// 
    /// WARNING: For production, use TPM-generated keys
    pub fn generate_key() -> [u8; 32] {
        let mut key = [0u8; 32];
        OsRng.fill_bytes(&mut key);
        key
    }
    
    /// Encrypt data with AES-256-GCM
    pub fn encrypt(&self, plaintext: &[u8]) -> Result<EncryptedData> {
        // Generate random nonce (96-bit for GCM)
        let mut nonce_bytes = [0u8; 12];
        OsRng.fill_bytes(&mut nonce_bytes);
        let nonce = GenericArray::from(nonce_bytes);
        
        // Encrypt
        let ciphertext = self.cipher
            .encrypt(&nonce, plaintext)
            .map_err(|e| anyhow!("Encryption failed: {}", e))?;
        
        Ok(EncryptedData {
            ciphertext: general_purpose::STANDARD.encode(&ciphertext),
            nonce: general_purpose::STANDARD.encode(&nonce_bytes),
            version: 1,
        })
    }
    
    /// Decrypt data
    pub fn decrypt(&self, encrypted: &EncryptedData) -> Result<Vec<u8>> {
        if encrypted.version != 1 {
            return Err(anyhow!("Unsupported encryption version: {}", encrypted.version));
        }
        
        // Decode base64
        let ciphertext = general_purpose::STANDARD
            .decode(&encrypted.ciphertext)
            .map_err(|e| anyhow!("Invalid ciphertext encoding: {}", e))?;
        
        let nonce_bytes = general_purpose::STANDARD
            .decode(&encrypted.nonce)
            .map_err(|e| anyhow!("Invalid nonce encoding: {}", e))?;
        
        if nonce_bytes.len() != 12 {
            return Err(anyhow!("Invalid nonce length: {}", nonce_bytes.len()));
        }
        
        let nonce_array: [u8; 12] = nonce_bytes.try_into()
            .map_err(|_| anyhow!("Failed to convert nonce to array"))?;
        let nonce = GenericArray::from(nonce_array);
        
        // Decrypt
        let plaintext = self.cipher
            .decrypt(&nonce, ciphertext.as_ref())
            .map_err(|e| anyhow!("Decryption failed: {}", e))?;
        
        Ok(plaintext)
    }
    
    /// Encrypt and save data to file
    pub fn encrypt_to_file<P: AsRef<Path>>(&self, plaintext: &[u8], path: P) -> Result<()> {
        let encrypted = self.encrypt(plaintext)?;
        let json = serde_json::to_string_pretty(&encrypted)?;
        std::fs::write(path, json)?;
        Ok(())
    }
    
    /// Load and decrypt data from file
    pub fn decrypt_from_file<P: AsRef<Path>>(&self, path: P) -> Result<Vec<u8>> {
        let json = std::fs::read_to_string(path)?;
        let encrypted: EncryptedData = serde_json::from_str(&json)?;
        self.decrypt(&encrypted)
    }
}

/// Key management for TPM integration
/// 
/// TODO: Implement actual TPM integration using tpm2-tss library
pub struct KeyManager {
    // In-memory key storage (INSECURE - for development only)
    master_key: [u8; 32],
}

impl KeyManager {
    /// Initialize key manager
    /// 
    /// TODO: Replace with TPM-backed implementation:
    /// 1. Check for existing sealed key in TPM
    /// 2. If not found, generate new key in TPM
    /// 3. Seal key to current PCR values
    /// 4. Return handle to TPM-protected key
    pub fn new() -> Result<Self> {
        tracing::warn!("⚠️  Using in-memory key storage. INSECURE for production!");
        tracing::warn!("⚠️  TODO: Implement TPM-backed key storage");
        
        // For development, load or generate key
        let master_key = Self::load_or_generate_key()?;
        
        Ok(Self { master_key })
    }
    
    /// Load existing key or generate new one
    /// 
    /// TODO: Replace with TPM key unsealing
    fn load_or_generate_key() -> Result<[u8; 32]> {
        const KEY_FILE: &str = "config/master.key";
        
        if Path::new(KEY_FILE).exists() {
            tracing::info!("Loading master encryption key from {}", KEY_FILE);
            let key_data = std::fs::read(KEY_FILE)?;
            if key_data.len() != 32 {
                return Err(anyhow!("Invalid key file length"));
            }
            let mut key = [0u8; 32];
            key.copy_from_slice(&key_data);
            Ok(key)
        } else {
            tracing::warn!("Generating new master encryption key");
            let key = EncryptionService::generate_key();
            
            // Ensure config directory exists
            if let Some(parent) = Path::new(KEY_FILE).parent() {
                std::fs::create_dir_all(parent)?;
            }
            
            std::fs::write(KEY_FILE, &key)?;
            tracing::info!("Master key saved to {}", KEY_FILE);
            
            Ok(key)
        }
    }
    
    /// Get encryption service with master key
    pub fn get_encryption_service(&self) -> Result<EncryptionService> {
        EncryptionService::new(&self.master_key)
    }
    
    /// Rotate master key (requires re-encrypting all data)
    /// 
    /// TODO: Implement key rotation workflow:
    /// 1. Generate new key in TPM
    /// 2. Re-encrypt all data with new key
    /// 3. Securely destroy old key
    /// 4. Update key reference
    pub fn rotate_master_key(&mut self) -> Result<()> {
        tracing::warn!("Key rotation not implemented yet");
        Err(anyhow!("Key rotation requires re-encryption of all data"))
    }
}

impl Default for KeyManager {
    fn default() -> Self {
        Self::new().expect("Failed to initialize key manager")
    }
}

/// Data access audit log entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataAccessLog {
    pub timestamp: chrono::DateTime<chrono::Utc>,
    pub user_id: String,
    pub operation: DataOperation,
    pub resource: String,
    pub success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DataOperation {
    Read,
    Write,
    Delete,
    Export,
}

/// Secure data storage with encryption and access logging
pub struct SecureStorage {
    encryption_service: EncryptionService,
    access_logs: Vec<DataAccessLog>,
}

impl SecureStorage {
    pub fn new(key_manager: &KeyManager) -> Result<Self> {
        Ok(Self {
            encryption_service: key_manager.get_encryption_service()?,
            access_logs: Vec::new(),
        })
    }
    
    /// Store encrypted data
    pub fn store(&mut self, key: &str, data: &[u8], user_id: String) -> Result<()> {
        let encrypted = self.encryption_service.encrypt(data)?;
        
        // TODO: Store in database with proper indexing
        let path = format!("data/encrypted/{}.json", key);
        if let Some(parent) = Path::new(&path).parent() {
            std::fs::create_dir_all(parent)?;
        }
        
        let json = serde_json::to_string(&encrypted)?;
        std::fs::write(&path, json)?;
        
        // Log access
        self.log_access(user_id, DataOperation::Write, key.to_string(), true);
        
        Ok(())
    }
    
    /// Retrieve and decrypt data
    pub fn retrieve(&mut self, key: &str, user_id: String) -> Result<Vec<u8>> {
        let path = format!("data/encrypted/{}.json", key);
        let json = std::fs::read_to_string(&path)?;
        let encrypted: EncryptedData = serde_json::from_str(&json)?;
        
        let plaintext = self.encryption_service.decrypt(&encrypted)?;
        
        // Log access
        self.log_access(user_id, DataOperation::Read, key.to_string(), true);
        
        Ok(plaintext)
    }
    
    /// Log data access event
    fn log_access(&mut self, user_id: String, operation: DataOperation, resource: String, success: bool) {
        let log = DataAccessLog {
            timestamp: chrono::Utc::now(),
            user_id,
            operation,
            resource,
            success,
        };
        
        // TODO: Persist to audit database
        tracing::info!("Data access logged: {:?}", log);
        self.access_logs.push(log);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_encryption_decryption() {
        let key = EncryptionService::generate_key();
        let service = EncryptionService::new(&key).unwrap();
        
        let plaintext = b"Patient data: XRD analysis results";
        let encrypted = service.encrypt(plaintext).unwrap();
        let decrypted = service.decrypt(&encrypted).unwrap();
        
        assert_eq!(plaintext.as_slice(), decrypted.as_slice());
    }
    
    #[test]
    fn test_encrypted_data_serialization() {
        let key = EncryptionService::generate_key();
        let service = EncryptionService::new(&key).unwrap();
        
        let plaintext = b"Sensitive medical data";
        let encrypted = service.encrypt(plaintext).unwrap();
        
        // Serialize to JSON
        let json = serde_json::to_string(&encrypted).unwrap();
        
        // Deserialize
        let deserialized: EncryptedData = serde_json::from_str(&json).unwrap();
        
        // Decrypt
        let decrypted = service.decrypt(&deserialized).unwrap();
        assert_eq!(plaintext.as_slice(), decrypted.as_slice());
    }
    
    #[test]
    fn test_wrong_key_fails() {
        let key1 = EncryptionService::generate_key();
        let key2 = EncryptionService::generate_key();
        
        let service1 = EncryptionService::new(&key1).unwrap();
        let service2 = EncryptionService::new(&key2).unwrap();
        
        let plaintext = b"Secret data";
        let encrypted = service1.encrypt(plaintext).unwrap();
        
        // Decryption with wrong key should fail
        assert!(service2.decrypt(&encrypted).is_err());
    }
}
