name: Prevent direct commits to main

on:
  push:
    branches:
      - main

jobs:
  no-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check for direct commits to main
        run: |
          if [ "$(git log -1 --pretty=%B)" != "Merge pull request"* ]; then
            echo "Prevent commits to the main branch."
            exit 2
          fi
